name: c5_elevate_online
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  injectable: 
  get_it:
  retrofit: ^4.9.0
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator:
  build_runner: 
  retrofit_generator: ^10.0.1
  json_serializable: ^6.10.0
  test: ^1.26.3
  
flutter:
  uses-material-design: true
